export * from './BlogAppPage'
export * from './CvPage'
export * from './EasyRestaurantPage'
export * from './GifAppPage'
export * from './HeroesPage'
export * from './MarcsPage'
export * from './MoviePage'
export * from './OrtodonciaPage'